### ISSUE TITLE
[Gnome 3.36] Issue with aplications menu with 2 monitors

### ISSUE THREAD

**Issue by NikSays** [micheleg/dash-to-dock#1136]
Distro: Manjaro 
Steps to replicate: 
- dash-to-dock set to left side of the screen
- have 2 monitor setup
- set primary monitor
  - directly below secondary, or
  - to the right of secondary, but a little lower 
- press applications button

Issue: application menu becomes smaller or entirely disappears (depending on monitor setup)
![Example](https://user-images.githubusercontent.com/9448754/77416529-9e036500-6dcc-11ea-9b05-5669f52a1293.jpg)

**Comment by gamedragon** [comment]
it happens only when "Panel mode: extend to the screen edge" is checked.

**Comment by darkdragon-001** [comment]
Icon is cropped in _Activites_ switcher:
![Yaru-Search-Problem](https://user-images.githubusercontent.com/177976/79502113-73a17200-802f-11ea-91c7-234af0682440.png)

Open windows are shown tiny:
![Yaru-Activities-Problem](https://user-images.githubusercontent.com/177976/79502121-77cd8f80-802f-11ea-8208-30c55a40e986.png)

I am running on Wayland. Further, my two monitors have very different DPI/Scaling (maybe related to [gnome-shell-tension-ubuntu-dock#1826543](https://bugs.launchpad.net/ubuntu/+source/gnome-shell-extension-ubuntu-dock/+bug/1826543)).

**Comment by vanvugt** [comment]
Fixed in 20e2b6a3417c46f5495925da584f03d86a895465 (which is included in dash-to-dock 68)

**Comment by vanvugt** [comment]
Please close this bug.

**Comment by drshaggy** [comment]
This is still an issue with one monitor in portrait mode as shown below.
Distro: Manjaro
Dash to dock version: 67
Steps to replicate: landscape monitor (left), landscape monitor (middle), portrait monitor (right). 
Same is true for 2 monitors; landscape (left and portrait (right). When the landscape monitor is the main monitor the activities switcher gets cropped etc.

This only happens when dock is docked top left and right and "Panel mode: extend to the screen edge" is checked. Thanks

![Screenshot from 2020-06-17 10-37-30](https://user-images.githubusercontent.com/15954937/84881993-844d8300-b086-11ea-891e-79ca193b15a0.png)
