### ISSUE TITLE
Dock not hiding 

### ISSUE THREAD

**Issue by TheAifam5** [micheleg/dash-to-dock#122]
Dock not hiding when system messages is showed (eg: shutdown message)
![screenshot from 2014-11-19 09 11 32](https://cloud.githubusercontent.com/assets/2192274/5106582/2396209e-6ffa-11e4-8f7c-c21035fc205c.png)

**Comment by vltr** [comment]
[+1]. This problem also occurs when I have an "always on top" window (away from the dock). Even if I'm focused in a fullscreen application, the dock does not hide unless I minimize the "always on top" window. For a better explanation, I have a secondary display which is configured to appear on all workspaces. Here's an example:

![screenshot from 2015-02-02 09 45 39](https://cloud.githubusercontent.com/assets/1540275/6000107/dbf07486-aac0-11e4-9b0a-aee203f0cd98.png)

Cheers,
Richard.

**Comment by micheleg** [comment]
Hi Richard,
I'm not sure if I undestood your problem. Can you reproduce it without a secondary monitor. I tried putting a window on "alwasy on top" but I can't notice the problem. Which version are you using?

I think the issue is unrelated to the previous, which I might have solve already but I still need some test.

**Comment by micheleg** [comment]
The original problem reported by @TheAifam5  should have been fixed by  950ca34cc7d5d3686560c733c1153f9e85cc14fa.

**Comment by vltr** [comment]
Hello @micheleg !

Well, first of I'm running Arch with Gnome 3.14, no extra repositories (except for infinality freetype patch and ck kernel). The problem persists without a secondary monitor, but it just happens when I change (pause for a screenshot) from one workspace to another using gnome's keyboard shortcuts (to the workspace that haves a "always on top" window). But, after changing window (focus to on top to focus again), the dash hides again and behaves normally. I don't know if this is the answer you're waiting, if I can provide more information, please let me know.

![screenshot from 2015-02-03 10 53 20](https://cloud.githubusercontent.com/assets/1540275/6020492/aec8c278-ab93-11e4-9f24-5b17ab565a87.png)

Best regards,
Richard.

**Comment by micheleg** [comment]
Hi @vltr ,
I think I can reproduce at least part of the problem. Could you check the branch bug_alwasy_on_top? It seems to solve the problem for me.

**Comment by vltr** [comment]
Hello @micheleg . I'm using that branch now and the problem still persists. The dock hides when an alert pops up, as an example. I can reproduce the problem everytime I change from a workspace without an always on top window to another which has, using the keyboard shortcuts. [Pause for a screenshot]. Maybe this is the issue (change workspace event) ?

Best regards,
Richard.

![screenshot from 2015-02-04 10 04 05](https://cloud.githubusercontent.com/assets/1540275/6040144/ab2705ea-ac55-11e4-89b6-eec0ae9295fa.png)

**Comment by micheleg** [comment]
Does the problem persist also if you disable the application based
intellihide option?

**Comment by vltr** [comment]
No, since it is always hidden and only the mouse pressure trigger it's
visibility.

**Comment by micheleg** [comment]
Disabling the "application based intellihide", not the whole intellihide option should not always hide the dash. Can you confirm?

**Comment by micheleg** [comment]
Also, is there any difference between current version and the  bug_alwasy_on_top branch? Could you doublecheck to be sure it is installed? Moreover, if you have any other extension installed pleas check if the problem persists disabling them.

Thank you!

**Comment by vltr** [comment]
Oh, yes, my mistake. Disabling just the "application based intellihide"
checkbox does fixes the problem :) The dock now hides just then there's an
application overlapping it, focused or not (I think this is the expected
result), with windows "always on top" or not. And yes, I'm using the branch
you asked for :)

For now this works good, but the application based intellihide is a very
nice option. Do you think this may work in the future?

Best regards,
Richard.

**Comment by micheleg** [comment]
I'll try to fix it as soon as I can reproduce it. I can see you have quite a few extension enabled on the screenshots above. Please confirm if the problem persist disabling **all** other extensions, and restarting the shell. Everything seems to be working for me, even with an external monitor.

**Comment by vltr** [comment]
Well, things got a little bit weird now. I turned off all extensions as you can see (almost) in the screenshot (sorry for its size). Well, I'm now typing on Chromium (which is not "on top"), but the "on top" window is blocking the dash, even though it's not active (I don't know which behaviour it should have). About the problem with a Dash that "doesn't hides" [pause-for-screenshot], I can't reproduce it anymore because it is always hidden (with "always on top" again), and the config is shown @ the screenshot too. I don't know, perhaps there's a "now known" problem with GS with multiple monitors and/or workspaces and its window algorithms?

![screenshot from 2015-02-09 18 38 11](https://cloud.githubusercontent.com/assets/1540275/6115286/b6008d30-b08b-11e4-9c46-b86089513f37.png)


PS 1: Yes, **I'm in the right git branch**.
PS 2: Yes, **everything is disabled** and **GS was reset**.
PS 3: If there's anything else I can provide, please, just ask :)

Best regards,
Richard.

**Comment by micheleg** [comment]
The expected behaviour is that an always on top windows will always be considered when deciding if the dash has to hide, regardless of the window having focus or not. From your description it seems everything is ok now. However, I don't understand if the problem was due to another extensions or if you were expecting a different behaviour.  Can you comment?

**Comment by vltr** [comment]
First of all, sorry for the late response. Well, I was expecting that the dash with application based intellhide option on would "ignore" always on top windows if they're not focused, like any other window. But, this was my understanding and there's no problem with the actual behaviour. I feel glad it is finally working with all these details explained and or fixed :) Thanks a lot!

**Comment by micheleg** [comment]
The idea is that an always on top window will obfuscate the dock, so it seems reasonable to me to hide it, which was not done before.

**Comment by micheleg** [comment]
Original issue closed by 950ca34cc7, subsequent one closed by a48626635e.

**Comment by vltr** [comment]
Oh, ok, it seems fine, thanks for your attention! :)
