### ISSUE TITLE
maximized windows resize to full screen and get cut off by dock

### ISSUE THREAD

**Issue by Be-ing** [micheleg/dash-to-dock#1370]
Sometimes maximized windows get resized to the entire area of the screen so part ends up getting hidden by the dock. I can work around this by unmaximizing then remaximizing the window, but it keeps happening so this gets quite frustrating. Here the bottom of the window is cut off:
![Screenshot from 2021-01-10 15-45-57](https://user-images.githubusercontent.com/9455094/104136417-89905900-535b-11eb-87e6-3334a5bddf79.png)

This is what it looks like properly maximized:
![Screenshot from 2021-01-10 15-46-23](https://user-images.githubusercontent.com/9455094/104136410-839a7800-535b-11eb-993f-cac57cb4eb05.png)

Using GNOME Shell 3.38.2 on Fedora 33 with Wayland.

**Comment by daekdroom** [comment]
I can confirm this happens on Arch Linux, GNOME Shell 3.38.3, Wayland, specially with Firefox, it's triggered every time I come back from the lock screen.

**Comment by cjao** [comment]
On my machine, this happens only in Wayland, not in an X11 session.

**Comment by SubF** [comment]
Same problem here with Gnome 3.38.3 and Wayland.

**Comment by plumlis** [comment]
same here

**Comment by vanvugt** [comment]
Downstream Ubuntu bug: https://bugs.launchpad.net/bugs/1917939

**Comment by Dimitri-Ba** [comment]
Same here, on archlinux

**Comment by Be-ing** [comment]
FWIW, this bug was annoying enough that I have since switched back to KDE.

**Comment by plumlis** [comment]
Seems devs fixed this in mutter
https://gitlab.gnome.org/GNOME/mutter/-/issues/1627
but don't know if they will backport to 3.38 or 3.36

**Comment by Be-ing** [comment]
Hooray I'll give GNOME 40 a try when Fedora 34 releases soon. This issue was so annoying that I switched back to KDE.

**Comment by viossat** [comment]
On a fresh install of Fedora 33 with GNOME 3.38.4 it happens when I resume from sleep. Switching to Xorg solves the issue.

**Comment by vanvugt** [comment]
This bug can probably close. It's been fixed in mutter instead per the above links.

**Comment by tronorama** [comment]
This is still present in GNOME 40. This happened just now after my Manjaro laptop ceased screen blanking:

![terminator-mutter-bug-after-screen-blank-still-present-in-gnome-40](https://user-images.githubusercontent.com/7062385/129456366-19c23146-cc09-4de0-ba9a-07dea0bc4f93.png)

**Comment by Susi-Sorglos** [comment]
same here, gnome 40.4 on fedora 34 using x11:

![Screenshot from 2021-09-09 10-52-45](https://user-images.githubusercontent.com/48016451/132655164-51c3ba31-bec2-4237-b3e4-2c0ea7e8e7ad.png)

**Comment by LuccoJ** [comment]
Yes, still present with mutter-41.3-1.fc35 and current Dash to Dock as of January 2022 (not actually sure how to see the version number). My computer has a defect in that it often thinks the lid is being briefly closed, and when that happens this bug almost invariably appears. It does mean a lot of window resizing.

**Comment by vanvugt** [comment]
New downstream Ubuntu bug: https://launchpad.net/bugs/1961508

**Comment by KaffeineKicks** [comment]
Confirmed and constantly reproducible on Wayland, Gnome 44, gnome-shell=44.5, libwayland=1.22.0, and dash-to-dock=v87.

Only happens with windows that maximized and inactive; active maximized window is restored correctly.

Overlapping does not depend on dock mode (dock/panel) or on dock placement (any screen side), present in any case. Occurs both after screen lock/unlock, and after sleep/wakeup with disabled screen auto-lock.

Only happens on Wayland session, while on X11 session the resizing works correctly.

**Comment by KaffeineKicks** [comment]
Confirmed and constantly reproducible on Wayland, Gnome 44, gnome-shell=44.5, libwayland=1.22.0, and dash-to-dock=v87.

Only happens with windows that maximized and inactive; active maximized window is restored correctly.

Overlapping does not depend on dock mode (dock/panel) or on dock placement (any screen side), present in any case. Occurs both after screen lock/unlock, and after sleep/wakeup with disabled screen auto-lock.

Only happens on Wayland session, while on X11 session the resizing works correctly.

**Comment by riffer33** [comment]
Solus, Gnome 44.3, Wayland.

At some point after some inactivity the dock just starts overlapping maximized windows.

I usually leave the extensions settings open so I can just change the position from bottom to one of the others and back and it starts working again for a while.

**Comment by acuteaura** [comment]
This shows up on NixOS 23.11. When waking up from suspend, all windows run through reflow before dash-to-dock loads and it remains broken until you Meta + Down and Meta + Up every window.

**Comment by jtherrmann** [comment]
Also seeing this on Debian 12 with GNOME 43.9 on Wayland, with the dock in the vertical-left position, set to always be visible. I have tried locking/unlocking the screen and suspending/resuming in order to intentionally reproduce it, but have not been able to. I have not yet noticed a pattern except that I'll switch back to some window and suddenly it's being overlapped by the dock. As others have stated, toggling the window's maximization state fixes it.

**Comment by riffer33** [comment]
Another way is to right click on the dock near the 9 dots thing and select settings.  Go to select position on screen and switch it to one of the other settings and then back.

I would note that I used Dash to Dock for Cosmic on Debian 12 and didn't have this problem.

**Comment by jtherrmann** [comment]
I enabled auto-hide in dash-to-dock since I realized I don't need the dock always visible anyway, but I also happened to stumble across this setting in dconf Editor and I'm curious if it resolves the issue for anyone (sorry if it's already been mentioned): `mutter / wayland / auto-maximize`

**Comment by alba-ado** [comment]
Still present in Ubuntu 24.04.3 with GNOME version 42.9 with wayland enabled. I have a dual-monitor setup and all windows get left behind the dock everytime I lock and unlock the screen.

**Comment by City-busz** [comment]
I submitted a patch to mutter that should fix this problem:
https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/3601

**Comment by balazscseh** [comment]
Still happening to me on Fedora 40 KDE, not only after sleep but from fresh boot too.
If i resize to a smaller window and then back full screen it solves the problem until the next boot.

**Comment by foegra** [comment]
> Still happening to me on Fedora 40 KDE, not only after sleep but from fresh boot too. If i resize to a smaller window and then back full screen it solves the problem until the next boot.

KDE?

**Comment by vanvugt** [comment]
It looks like dash-to-dock never needed fixing, only Mutter. The latest information is in https://bugs.launchpad.net/bugs/1961508
