### ISSUE TITLE
Prevent dock from popping out when gnome is in do-not-disturb

### ISSUE THREAD

**Issue by madzaf** [micheleg/dash-to-dock#1634]
Hello,
Whenever I receive a message on Microsoft Teams, the dock pop outs and show the teams icon wiggling before hiding again. It does this several times in a row for each new message received and it is very distracting (especially when in full screen in another application, for instance a remote desktop).
I've attached a screen capture so you can see what I'm talking about.
Is there a way to stop the dock from showing up when receiving these notifications ? At lease when gnome is set as "do-not-disturb" ?
Thank you

https://user-images.githubusercontent.com/2269141/149095563-9accef52-55bf-47b0-a3b4-777fec4562cf.mov

**Comment by gnolooo** [comment]
I was about to post the same issue. Best thing would be to keep both features with the possibility to switch between them at will.
Imho, this shouldn't depend on "Do-not-disturb" mode 'cause, at least for my use of it, I always keep it on (I hate notifications), but sometimes I find useful to have the dock popping out if i have a message (imho it's better than a notification with the content of the message), so I'd like to switch between "Popping dock" and "Not popping dock" regardless of "Do-not-disturb" mode.

**Comment by apollotonkosmo** [comment]
:+1:

**Comment by paul-vd** [comment]
I also find this behavior really annoying.

 We already receive notifications, so no need for the dock to pop up, as @gnolooo suggested, a setting to disable this would be very welcoming.

**Comment by hmlendea** [comment]
It's especially annoying when you're screensharing and you're coworkers are like "bro wtf" especially when everyone is using Windows and I'm the only penguin... and issues like this sure doesn't make Linux look good.

**Comment by rlees85** [comment]
Another vote for adding an option to disable this without relying on do not disturb. I don't use do not disturb often as I like notifications but I can't be doing with the dash to dock wanting to cover my terminal everytime it beeps or someone sends a message on teams/slack.

**Comment by leandrokemp** [comment]
This should be resolved now. @madzaf could you please check if it's working now and close this issue?

**Comment by madzaf** [comment]
I've re-installed the extension using Gnome-Extension and it seems the issue is still there. I'm using version 73 on Gnome 42. 
Should I install it manually from github?

**Comment by leandrokemp** [comment]
Version 73 already have this feature. You have go to the extension intelligent settings and uncheck the option to show dock for urgent notifications, as below.

![image](https://user-images.githubusercontent.com/41006452/188616501-41204a83-26a8-4e12-9d5f-014b4b0a4c34.png)

![image](https://user-images.githubusercontent.com/41006452/188616694-78d11bc3-b249-4650-ab19-b16123026a0c.png)

**Comment by madzaf** [comment]
Yes it looks like it works. I am wondering what is considered an urgent notification and what isn't. I'd say most of the times the notifications coming from Teams aren't necessarily urgent unless they are directed at me specifically. Anyway to customize this by any chance ?

**Comment by leandrokemp** [comment]
What I have noticed during the tests is that any notification coming from Teams is considered as urgent. As far as I know it's the app that decides what kind of notification it will send.

**Comment by madzaf** [comment]
Fair enough ! I'm closing this issue. Thank you for this !
