### ISSUE TITLE
[BUG] Lock the screen on Overview or Applications crashes Gnome

### ISSUE THREAD

**Issue by EricwanAR** [micheleg/dash-to-dock#2329]
Specs:
Debian Testing, Gnome-shell 47.0-3, libmutter-15-0 47.0-3, dash to dock v99

Problem reproduce:
- disable all extensions
- go to overview or applications and lock the screen, works just fine
- enable dash to dock
- go to overview or applications and lock the screen
- Gnome crashes and showing the 'Oh no! Something has gone wrong.' screen.
- crash screen reload once and then normally locked the screen.
- after unlock the crash screen persists but can access to overview and applications by super key

here's the log by `journalctl --since '1 minutes ago' > ./crash.txt`
[crash.txt](https://github.com/user-attachments/files/17685639/crash.txt)

**Comment by smolBlackCat** [comment]
I'm having this exact same issue. I also happen to use the Debian Testing, could it be something related to some recent update to gnome packages? As far as I can remember, this issue began happening after some gnome package update but I'm not 100% sure

**Comment by smolBlackCat** [comment]
These log messages might give an insight of what's happening

```
Code: 00 00 00 48 8b 44 24 10 49 83 ed 08 49 39 c5 0f 84 c9 02 00 00 48 8b 83 28 01 00 00 4c 89 e6 4a 8b 2c 28 48 8b 45 00 48 8b 00 <48> 8b 38 e8 a9 8b fd ff 41 89 c6 85 c0 75 ca 8b 05 3c 16 03 00 4c

gnome-shell[9571]: segfault at 55cb00000001 ip 00007fd698ee95cf sp 00007ffd26559c60 error 4 in libst-15.so[475cf,7fd698ebf000+54000] likely on CPU 2 (core 2, socket 0)
```

It seems that this crash used to happen to [dash-2-panel](https://github.com/home-sweet-gnome/dash-to-panel/issues/976) as well and it got fixed by this [merge request](https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1230).

**Comment by smolBlackCat** [comment]
Surprisingly, the shell does not crash if I manually click the lock screen button in the overview. @EricwanAR, may you check on your system if that is also the case?

### Demonstration


https://github.com/user-attachments/assets/f9cc9189-fbb7-4599-8344-64643c737fd2

**Comment by EricwanAR** [comment]
> Surprisingly, the shell does not crash if I manually click the lock screen button in the overview. @EricwanAR, may you check on your system if that is also the case?
> 

It still crashes this way.

> Is there anyone that can confirm that this error also happens on GNOME 47.1?

Debian recently pushed muttur 47.1-2 to testing but not gnome-shell, so i did a testing-ustable-mix to update then alltogether to 47.1-2. Though the crash persists.

**Comment by vanvugt** [comment]
Duplicate of #2179.

The fix is proposed in https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/3252

**Comment by smolBlackCat** [comment]
> Duplicate of #2179.
> 
> The fix is proposed in https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/3252

Just backported your patch into my system, it is all working well now. Thanks for your great work

**Comment by EricwanAR** [comment]
> Duplicate of #2179.
> 
> The fix is proposed in https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/3252

@vanvugt Thank you for your great effort. By the way I checked Debian's repo history of gnome shell and found out that [your commit for this patch](https://salsa.debian.org/gnome-team/gnome-shell/-/commit/16c5cf01ddfc8e7375ef36ad650e90c6d40c352f) seems got accidentally reverted in  [this commit](https://salsa.debian.org/gnome-team/gnome-shell/-/commit/d21337c6b89ea6243092e60b5b542308d5cea056). Is it possible to roll it back?

**Comment by vanvugt** [comment]
Thanks @EricwanAR, I have [committed a fix](https://salsa.debian.org/gnome-team/gnome-shell/-/commit/a0d949e0ea2f201b4f3f1e0104f61a95a390cc62) and asked for a Debian developer to publish it.
