### ISSUE TITLE
gnome-shell-ext dumping core whenever I try to open config settings

### ISSUE THREAD

**Issue by bulletmark** [micheleg/dash-to-dock#262]
I am using current Arch Linux with stock gnome-shell 3.18.3-1 and current v49 from extensions.gnome.org. Whenever I try to open the config settings for dash-to-dock I get the following core dump. This happens opening from either gnome-tweak-tool or from extensions.gnome.org using any browser.
```
Dec 03 09:07:50 marklt gnome-session[848]: gnome-shell-extension-prefs: cairo-surface.c:928: cairo_surface_reference: Assertion `(_cairo_atomic_int_get (&(&surface->ref_coun\
t)->ref_count) > 0)' failed.
Dec 03 09:03:55 marklt systemd-coredump[1791]: Process 1782 (gnome-shell-ext) of user 1000 dumped core.
                                               
                                               Stack trace of thread 1782:
                                               #0  0x00007fec1baed5f8 raise (libc.so.6)
                                               #1  0x00007fec1baeea7a abort (libc.so.6)
                                               #2  0x00007fec1bae6417 __assert_fail_base (libc.so.6)
                                               #3  0x00007fec1bae64c2 __assert_fail (libc.so.6)
                                               #4  0x00007fec19167aa0 cairo_surface_reference (libcairo.so.2)
                                               #5  0x00007febff1d26d8 n/a (librsvg-2.so.2)
                                               #6  0x00007febff1e1fec n/a (librsvg-2.so.2)
                                               #7  0x00007febff1d5fd0 n/a (librsvg-2.so.2)
                                               #8  0x00007febff1d5fd0 n/a (librsvg-2.so.2)
                                               #9  0x00007febff1d5fd0 n/a (librsvg-2.so.2)
                                               #10 0x00007febff1d6492 n/a (librsvg-2.so.2)
                                               #11 0x00007febff1d6da8 n/a (librsvg-2.so.2)
                                               #12 0x00007febff1e34d3 rsvg_handle_render_cairo_sub (librsvg-2.so.2)
                                               #13 0x00007febff1e39c8 rsvg_handle_get_pixbuf_sub (librsvg-2.so.2)
                                               #14 0x00007febff3efef6 n/a (libpixbufloader-svg.so)
                                               #15 0x00007fec19e8fd02 n/a (libgdk_pixbuf-2.0.so.0)
                                               #16 0x00007fec19e9187a gdk_pixbuf_new_from_file (libgdk_pixbuf-2.0.so.0)
                                               #17 0x00007fec1ab0fd5f gtk_builder_value_from_string_type (libgtk-3.so.0)
                                               #18 0x00007fec1ab10135 n/a (libgtk-3.so.0)
                                               #19 0x00007fec1ab1043f n/a (libgtk-3.so.0)
                                               #20 0x00007fec1ab11a75 n/a (libgtk-3.so.0)
                                               #21 0x00007fec1ab13401 n/a (libgtk-3.so.0)
                                               #22 0x00007fec1c0c8317 n/a (libglib-2.0.so.0)
                                               #23 0x00007fec1c0c913e g_markup_parse_context_parse (libglib-2.0.so.0)
                                               #24 0x00007fec1ab137e6 n/a (libgtk-3.so.0)
                                               #25 0x00007fec1ab0dac1 gtk_builder_add_from_file (libgtk-3.so.0)
                                               #26 0x00007fec19a381f0 ffi_call_unix64 (libffi.so.6)
                                               #27 0x00007fec19a37c58 ffi_call (libffi.so.6)
                                               #28 0x00007fec1cbbfd4b n/a (libgjs.so.0)
                                               #29 0x00007fec1cbc122f n/a (libgjs.so.0)
                                               #30 0x00007fec1b4064a2 n/a (libmozjs-24.so)
                                               #31 0x00007fec1b40a2c9 n/a (libmozjs-24.so)
                                               #32 0x00007fec1b413c38 n/a (libmozjs-24.so)
                                               #33 0x00007fec1b4062da n/a (libmozjs-24.so)
                                               #34 0x00007fec1b51a91b n/a (libmozjs-24.so)
                                               #35 0x00007fec1b406324 n/a (libmozjs-24.so)
                                               #36 0x00007fec1b415c43 n/a (libmozjs-24.so)
                                               #37 0x00007fec1b660048 n/a (libmozjs-24.so)
                                               #38 0x00007fec1d241aa2 n/a (n/a)
~~~

**Comment by bulletmark** [comment]
I should add that other extension config settings do open fine.

**Comment by Brainwall** [comment]
Yes me too do not open setting gnome-shell 3.18 and current v49.

"cairo-surface.c:928: cairo_surface_reference: Assertion `(_cairo_atomic_int_get (&(&surface->ref_count)->ref_count) > 0)' failed.
Aborted (core dumped)"

**Comment by bulletmark** [comment]
Same thing happens with current master branch.

**Comment by micheleg** [comment]
Very strange, did it happen after some sort of upgrade of GNOME and related libraries? 3.18 and v49 has been out for a while and it is the first time this quite evident bug reported. @Brainwall: I guess the bug report on the extension website is from you.

**Comment by Brainwall** [comment]
Yes bug report on the web site is by me. 
Maybe new libaries i dont now because yesterday installed new fresh Archlinux and gnome. BUT a week ago in my arch and dash to dock work normal in my PC (INTEL GPU Integrated) yesterday buy new graphics a reinstall arch and dash to dok no work open setting maybe Nvidia driver ?

**Comment by Brainwall** [comment]
I FIXED :D remove all files media in (/home/you/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com)

i dont now but i try open this folder in nautilus and NAUTILUS crash :D ok my test remove all file in  media folder and Dash To Dock is normal open setting :D 

PD : use terminal to delete all files in media

**Comment by Brainwall** [comment]
Ok testing more in media LOGO.SVG error buggy all fiel ok but LOG.SVK crashing everything...

**Comment by micheleg** [comment]
That's really strange. Can you confirm that reinstalling the extension the error persist? It could be that the LOGO.svg file contains inkspace specific tags, or whatever, and some newer version of the svglib used by GNOME crashes with it. I guess that if Nautilus crash for a malformed svg it might be worth filing a bug upstream once we understand the relevant module involved.

**Comment by Brainwall** [comment]
uninstall and install from https://extensions.gnome.org/extension/307/dash-to-dock/ back and still crash.

**Comment by ssbb** [comment]
Same thing here. Installed arch (nov release) about one week ago and everything work fine. But when installed arch (dec release) yesterday on some hardware can't open settings (with error mentioned by @Brainwall )

**Comment by ssbb** [comment]
After removing logo.svg everything looks fine

**Comment by ssbb** [comment]
gnome-shell version from arch official repos: 3.18.3

**Comment by micheleg** [comment]
I don't know how Arch Linux works, if it is something feasible, could anybody check if downgrading librsvg to the previous version (now you should have librsvg 1:2.40.12-1) solves the problem?

**Comment by bulletmark** [comment]
OK, I find there is an Arch bug opened about this, see https://bugs.archlinux.org/task/47245.

**Comment by jperrin** [comment]
I see this as well on fedora23 (just installed today). indeed removing logo.svg appears to have resolved the issue.

**Comment by dffischer** [comment]
One can also use a tool not affected by the bug, e.g. ImageMagick, to convert the SVG to a PNG and replace all occurrences of `logo.svg` with `logo.png` throughout the entire extension source code to restore complete functionality. At least, that is what I do with [the Arch Linux package sourcing from this Git repository](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=gnome-shell-extension-dash-to-dock-git&id=9dec3e5adff0e0ce168eca3a04e99b89c0e54396#n31) until the problem is fixed.

**Comment by micheleg** [comment]
Given that this is not a bug in the extension itself but rather on librsvg (not toally sure about this), did anybody submit an bug report upstream? I can't reproduce the bug on my Debian stable system :)

**Comment by dffischer** [comment]
Yes, [The Arch Linux Bug report](https://bugs.archlinux.org/task/47245) @bulletmark already mentioned also lead to [an entry in the GNOME Bugzilla](https://bugzilla.gnome.org/show_bug.cgi?id=759084).

**Comment by iticus** [comment]
I had the same error when using xfce4-appfinder on my Arch install:
```
xfce4-appfinder: cairo-surface.c:928: cairo_surface_reference: Assertion `(_cairo_atomic_int_get (&(&surface->ref_count)->ref_count) > 0)' failed.
```
As @micheleg pointed out the bug is caused by the recent update of [librsvg](https://wiki.gnome.org/action/show/Projects/LibRsvg?action=show&redirect=LibRsvg) (version 2.40.12-1).
For the moment I fixed my problem by downgrading the package to 2.40.11-1 using the [Arch Linux Archive] (https://wiki.archlinux.org/index.php/Arch_Linux_Archive); perhaps it helps others too.

**Comment by fastrizwaan** [comment]
ya, deleting the logo.svg causes the settings to work, 

rm ./share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/media/logo.svg

**Comment by goedine** [comment]
I downgraded the librsvg package and the problem is solved. I also reported a bug for Fedora 23. Hope they will fix it. Can anybody tell me how to delete or rename the logo.svg to png? I am using Fedora not Arch.

**Comment by freddyw** [comment]
Right, I also filed a bug for Fedora 23: https://bugzilla.redhat.com/show_bug.cgi?id=1291226 . Ah well, better 2 than none, right?

I used Gimp to convert the svg to png. I attached my converted logo. Rename it to svg and drop it in the media folder.

![logo](https://cloud.githubusercontent.com/assets/1209921/11780081/92c60464-a25f-11e5-8868-5310f9764202.png)

**Comment by goedine** [comment]
Thank you Freddy, but how do I find or open the file for this extension? Do I need to open Nautilus as root?

**Comment by freddyw** [comment]
When downloaded via the extensions website, put it in the $HOME/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/media/ folder. No need to do that as root.

**Comment by goedine** [comment]
There are two problems, all my other extensions show, except for this
one. 
When I try to open it through the terminal, nautilus crashes.

**Comment by goedine** [comment]
I found the solution, at least for Fedora 23, first downgrade the package the librsvg, then open it with nautilus naturally and change logo.svg to logo.png, meanwhile I hope the bug gets fixed, so that we won't have to do such things again. If you don't downgrade the package, nautilus can't open it.

**Comment by edwinfoss** [comment]
The options panel won't open because the logo.svg file then I tried to discover what is wrong with the file comparing with others svg files, but no results, after that I tried to modify the file directly into the inkscape checking which object trigger the cairo flaw and the cursor shadow object was the problem, also I noticed that exists 3 more arrows under the cursor. To obtain the same shadow effect you need only 2 arrows, the cursor and the arrow that will be the shadow, to make the arrow turn in shadow use the function blur bar inside the fill and stroke options. To set how dark will be the shadow change alpha value from color or change opacity value in opacity bar.
After these changes also it will work even on librsvg 2.40.12

**Comment by lucaciavatta** [comment]
I have the same issue on Fedora 23 (with kernel 4.4 rc6 nodebug) and also Nautilus crashed trying open the media folder. Thanks to @edwinfoss workaround, I simple opened logo.svg in Inkscape and removed the arrow. Next, saved overwriting the file. After that, all works fine.

**Comment by edwinfoss** [comment]
I think it's related to a filter applied and grouping some objects, also I found on steam.svg included in faenza icon theme.
Here is the fail proof file:
[logo.svg.zip](https://github.com/micheleg/dash-to-dock/files/69474/logo.svg.zip)

**Comment by micheleg** [comment]
Thanks @edwinfoss  and @lucaciavatta  for the additional information. @edwinfoss would you mind uploading the updated version of the inkscape svg which is not triggering the bug?

**Comment by edwinfoss** [comment]
@micheleg No, completely not, the file is yours, here is:
[logo.svg.zip](https://github.com/micheleg/dash-to-dock/files/70254/logo.svg.zip)
And thank you for the great extension! d(^-^)b

**Comment by micheleg** [comment]
@edwinfoss  Thanks.

**Comment by micheleg** [comment]
I have updated the logo in the master branch with the version provided by @edwinfoss which should avoid triggering the bug in librsvg.

**Comment by edwinfoss** [comment]
Sorry for bother you again (^_^;)q
Finally I found the error on logo.svg, it was a non existent member, "filter:url(#filter4365-3)", I made the changes directly on svg script and made the corrections.
...and, if you want to check what was wrong, you can see with meld or with the program you like, here is both files:
[dock-to-dock-icon.zip](https://github.com/micheleg/dash-to-dock/files/71271/dock-to-dock-icon.zip)

May librsvg lost some compatibility with some function or they removed some "ignore exception"?

Thank you so much,
Best regards and merry xmas,
Edwin

**Comment by kanishkablack** [comment]
latest build solved the issue

**Comment by dffischer** [comment]
The [upstream bug at GNOME](https://bugzilla.gnome.org/show_bug.cgi?id=759084) was recently fixed. Arch Linux also shipped out a fixed version. So it would now even be possible to use the old `logo.svg` again. Thus, I suggest closure of this issue.

**Comment by micheleg** [comment]
Good. I might prefer to keep the new version of the logo to avoid breaking not yet updated installations. Was there any significant changes in it?

**Comment by dffischer** [comment]
I compared both variants with ImageMagick, Firefox, Eye of GNOME, GIMP and Inkscape, while my system hat a fixed librsvg installed.

Firefox does not show any pointer with both and no colors in the background, but at least has the shadow in the new variant.

ImageMagick and Inkscape show only a slight difference in tone, darkening the shadow of the mouse pointer a little in the new variant.

When looking at the new variant in Eye of GNOME and GIMP, the lower end of the shadow is cut. Looking closely, I can spot this effect in the preferences window of the extension, too. I assume these are the ones most close to GTK, thus using librsvg.

I am no SVG expert, so I cannot explain, why the shadow is cut. I hope this screenshot of the phenomenon can aid in your decision on which variant to keep around for the long term.

![cut shadow](https://cloud.githubusercontent.com/assets/6497034/12875225/d25e12c2-cde5-11e5-8a4e-e3fc384823b6.png)

**Comment by micheleg** [comment]
Thanks. That icon is far from a piece of art anyway, thus for the moment I'll stick to it.
